### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by mkoch227** [mkoch227/ets2-mobile-route-advisor#22]
- [x] Update feature list in the `README` to include mini-map support
- [ ] Update screenshots to showcase the new look and mini-map
- [x] Add contributors section to `README`

**Comment by mkoch227** [comment]
@denilsonsa, I was working on new screenshots, and I noticed that the markup for showing the gear shifter icon on the top row was commented out. Any reason why? I enabled it temporarily and it looked good to me... I just wasn't sure if I was missing anything.

**Comment by denilsonsa** [comment]
The reason was because it was taking too much valuable space, specially because the weekdays were not abbreviated.

Now that you have enabled the gear icon and shortened the weekday, we may want to reduce the `flex-basis: 9em` from `div._time`. We may also increase `flex-basis: 2em` to `2.5em` or `3em` (maybe in a new rule just for the gear). Anyway, just try testing it by resizing the window (like [in here](https://youtu.be/26BqmAyqw5g)).

**Comment by mkoch227** [comment]
I modified the CSS so that `div._time` and `div._speed` share the same width (I'm not sure if the in-game advisor uses the same length for both sections or not.... I'm RDP'ed into my Windows box so I can't check it out yet). I also gave `div._gear` it's own rule to increased `flex-basis` to 2.5. It seems to work well so far.

**Comment by denilsonsa** [comment]
> I'm not sure if the in-game advisor uses the same length for both sections or not

I just checked a screenshot, speed was about 90px, time was about 110px.

Still, as long as everything fits nicely, that's fine. :)
