### ISSUE TITLE
New Layout Has Issues in Safari

### ISSUE THREAD

**Issue by mkoch227** [mkoch227/ets2-mobile-route-advisor#26]
Tested on OS X 10.10.5:
![screen shot 2015-10-03 at 3 51 38 pm](https://cloud.githubusercontent.com/assets/333430/10264856/f35a1b0a-69e6-11e5-98b6-8b65788129a2.png)

**Comment by mkoch227** [comment]
It looks like the `flex-` properties aren't supported in Safari until Safari 9 (which I believe was released with El Capitan?) Safari 6.1+ supports flex with the `-webkit-` vendor prefix, so adding those in should make things a bit better.

| Browser | Compatibility without vendor prefix | Compatibility with vendor prefix |
|------------|----------------------------------------------|-------------------------------------------- |
| Chrome | 29.0 | `-webkit-` 29.0 |
| Firefox | 28.0 | `-moz-` 18.0 |
| IE | 11.0 | `-ms-` 10.0 |
| Safari | 9.0 | `-webkit-` 6.1 |
| Opera | 17.0 | 17.0 (never used vendor prefixes) |

**Comment by denilsonsa** [comment]
IMHO, this is the approach that makes more sense. Let's use the standard properties first, and if any current browser has problems, then we add vendor prefixes. This avoids polluting the CSS with stuff that is not needed.

Useful link: http://caniuse.com/#feat=flexbox

I wonder if we really need to support IE10, since IE11 is already out. Not that it matters that much, now that the prefixes have been added.
